# Homework 5
____
## Questions 1-6

1. Pandas stands for "Panel Data", but is said to also reference "Python Data Analysis".

1. The two collections used in Pandas are series and dataframes.

1. Pandas is able to used for statistical analysis, data normalization, data visualization, and data inspection.
1. To premanently sort a DataFrame with the df.sort() method, the key phrase would be `inplace = True`.
1. CSV files, or comma separated value files, are plain text files with a format used recording tabular data.
1. Contending with null values is one of the key components of cleaning and preparing data for analysis.

In [ ]:
### Question 7

import numpy
Ray1 = numpy.ones(12).reshape(2,3,2)
print(Ray1)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
### Question 8

import numpy
Ray2 = numpy.linspace(0, 20, num = 6)
print(Ray2)

### Question 9
import copy
Ray3 = copy.deepcopy(Ray2)
print(Ray3)
print(id(Ray2) != id(Ray3))

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
True


In [ ]:
### Question 10

import numpy
a_ray = ([[25, 16]])
b_ray = ([[11, 2], [13, 4]])
c_ray = ([[7, 81], [5, 6], [11, 12]])
newArray = numpy.concatenate((a_ray, b_ray, c_ray))
print(newArray)

### Question 11

sortedArray = numpy.sort(newArray)
print(sortedArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [18]:
### Question 12

import numpy
Ray4 = Ray1.reshape(4,3)
Ray4a, Ray4b, Ray4c, Ray4d = Ray4
print(" Ray4a", Ray4a,"\n Ray4b", Ray4b,"\n Ray4c", Ray4c,"\n Ray4d", Ray4d)

 Ray4a [1. 1. 1.] 
 Ray4b [1. 1. 1.] 
 Ray4c [1. 1. 1.] 
 Ray4d [1. 1. 1.]


In [ ]:
### Question 13

import numpy
one = numpy.array([10, 11, 12, 13, 14, 15, 16, 17])
two = numpy.array([20, 21, 22, 23, 24, 25, 26, 27])
three = numpy.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = numpy.concatenate((one, two, three))
comboArray.sort()
print(comboArray)

### Question 14
## I was somewhat confused by the directions on this part.
## Please let me know if I misconstrued their meanings.

print("sec1 is", comboArray[1])
print("sec2 is", comboArray[2:])
print("sec3 is", comboArray[3:14])
print("sec4 is", comboArray[-6:])
print("sec5 is", comboArray[-24:-10])
print("sec6 is", comboArray[16::2])
print("sec7 is", comboArray[23::-5])





[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1 is 1
sec2 is [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 is [ 3  4  5  6  7 10 11 12 13 14 15]
sec4 is [22 23 24 25 26 27]
sec5 is [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6 is [20 22 24 26]
sec7 is [27 22 15 10  3]


In [7]:
### Question 15

import pandas
Ingredients = pandas.Series(["Flour", "Milk", "Eggs", "Spam"], name= "Ingredients")
Quantity = pandas.Series([4, 1, 2, 1], name= "Quantity")
Unit = pandas.Series(["cups", "cup", "large", "can"], name= "Unit")

Dinner = pandas.concat([Ingredients, Quantity, Unit], axis= 1)
print(Dinner)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [24]:
### Question 16

import pandas
studentinfo = {
            'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pandas.DataFrame(studentinfo)
print(studentData)

### Question 17
## I think the third element is supposed to be "waffles",
#  but I wasn't sure, so I left it how it was.

studentData["dessert"] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
print(studentData)

### Question 18

studentData.sort_values(by= ["Name", "address"], inplace= True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        dessert  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  
      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot        

In [ ]:
### Question 19
## Could you explain this "disc" you want me to save it to.

import pandas

df = pandas.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cow_and_goats.csv")

### Question 20

veggies = pandas.DataFrame({"Tomato": [20, 24, 18], "Onion": [12, 17, 19], "Leek": [8, 11, 10]}, index= ["John", "Paul", "Ringo"])
veggies.to_csv("Veggies_1.csv")

veg2 = pandas.read_csv("Veggies_1.csv", index_col= 0)
veg3 = veg2.replace(to_replace= 10, value= 100)
veg3.to_csv("Veg3.csv")